name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  ai-functional-tests:
    uses: sutapamaji/playwright-ai-action/.github/workflows/playwright-ai-test.yml@main
    with:
      start_command: "npx serve src -p 3000 -s"
      app_port: "3000"
    secrets: inherit
