name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  ai-functional-tests:
    uses: sutapamaji/playwright-ai-action/.github/workflows/playwright-ai-test.yml@main
    with:
      start_command: "npm start"
      app_port: "3000"
    secrets:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}